// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nomenclatures;

namespace Nomenclatures.Migrations
{
    [DbContext(typeof(NomenclaturesContext))]
    [Migration("20211014072726_InitialisationDb")]
    partial class InitialisationDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nomenclatures.FamilleMatierePremiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan?>("DureeOptimaleUtilisation")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("FamilleMatierePremiere");
                });

            modelBuilder.Entity("Nomenclatures.MatierePremiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("DureeConservation")
                        .HasColumnType("time");

                    b.Property<int?>("FamilleId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PoidsUnitaire")
                        .HasColumnType("float");

                    b.Property<int>("PourcentageHumidite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamilleId");

                    b.ToTable("MatieresPremieres");
                });

            modelBuilder.Entity("Nomenclatures.MatierePremiere", b =>
                {
                    b.HasOne("Nomenclatures.FamilleMatierePremiere", "Famille")
                        .WithMany()
                        .HasForeignKey("FamilleId");

                    b.Navigation("Famille");
                });
#pragma warning restore 612, 618
        }
    }
}
